name: Deploy media to S3

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
    paths: ["media/**", ".github/workflows/deploy-media-to-s3.yml"]

env:
  AWS_REGION: ca-central-1
  S3BUCKET: fortunoff-media-public

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy media to S3 bucket
        run: |
          aws s3 sync ./media s3://${{ env.S3BUCKET }}/critical-editions --delete --acl public-read
      - name: Invalidating Cloudfront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E3HZDQWL860EH9 --paths "/critical-editions/*"
